const assert=require('assert'),path=require('path');const {pathToFileURL}=require('url')
class ClassList{constructor(){this.s=new Set()}add(...x){x.forEach(v=>this.s.add(v))}remove(...x){x.forEach(v=>this.s.delete(v))}toggle(v,on){if(on===undefined){if(this.s.has(v)){this.s.delete(v);return false}this.s.add(v);return true}on?this.s.add(v):this.s.delete(v);return on}}
class El{constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.style={};this.classList=new ClassList();this.hidden=false;this._html='';this.textContent='';this.parentElement=null}set id(v){this._id=v}get id(){return this._id}set className(v){this._className=v;String(v).split(/\s+/).filter(Boolean).forEach(x=>this.classList.add(x))}get className(){return this._className||''}set innerHTML(v){this._html=String(v)}get innerHTML(){return this._html}append(...els){for(const e of els){e.parentElement=this;this.children.push(e)}}remove(){if(this.parentElement)this.parentElement.children=this.parentElement.children.filter(x=>x!==this)}insertAdjacentElement(_where,e){this.parentElement?.append(e)}setAttribute(){}focus(){}querySelector(){return null}closest(){return null}}
const body=new El('body'),shell=new El('main'),runbar=new El('section'),v12tools=new El('section'),badge=new El('span');runbar.id='runbar';v12tools.id='v12-tools';badge.id='badge';body.append(shell);shell.append(runbar,v12tools,badge)
const byId=new Map([['runbar',runbar],['v12-tools',v12tools],['badge',badge]])
const listeners=new Map();global.document={body,documentElement:new El('html'),fullscreenElement:null,querySelector(sel){if(sel==='.shell')return shell;if(sel==='.codex-scroll')return null;if(sel.startsWith('[data-action'))return null;return null},getElementById(id){return byId.get(id)||null},createElement(tag){return new El(tag)},addEventListener(name,fn){const a=listeners.get(name)||[];a.push(fn);listeners.set(name,a)},execCommand(){return true},exitFullscreen(){}}
document.documentElement.requestFullscreen=()=>Promise.resolve()
global.MutationObserver=class{constructor(fn){this.fn=fn}observe(){}disconnect(){}}
const store=new Map();global.localStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)}
global.navigator={clipboard:{writeText:async()=>{}},serviceWorker:{register:async()=>({})}}
global.window={addEventListener(){},removeEventListener(){},__abyssal:null,__abyssalV12:null}
const eventHandlers=new Map(),game={scene:{audio:{setVolumes(s,a){this.last=[s,a]}}},events:{on(name,fn){eventHandlers.set(name,fn)}}}
const state={mode:'title',seed:'',floor:1,archetype:null,steps:0,level:1,secretCount:0,runStats:{kills:0,bossesDefeated:0,elitesDefeated:0,damageTaken:0,retreats:0}}
window.__abyssal={send(){},getState:()=>structuredClone(state),getGame:()=>game,getLanguage:()=> 'en',setLanguage(){}}
window.__abyssalV12={getCodex:()=>({enemies:[],items:[],floors:[],notes:[],endings:[],secrets:[]})}
;(async()=>{await import(pathToFileURL(path.resolve(__dirname,'../docs/v13.js')).href+`?t=${Date.now()}`);assert(window.__abyssalV13,'v1.3 runtime API missing');assert(v12tools.parentElement.children.some(e=>e.id==='v13-tools'),'v1.3 toolbar was not mounted');const tools=v12tools.parentElement.children.find(e=>e.id==='v13-tools');assert(tools.innerHTML.includes('data-v13="settings"'));assert(tools.innerHTML.includes('data-v13="daily"'));assert(tools.innerHTML.includes('data-v13="achievements"'));window.__abyssalV13.openSettings();assert(body.children.some(e=>e.className==='v13-modal'&&e.innerHTML.includes('Advanced options')),'Settings modal failed');window.__abyssalV13.openDaily();assert(body.children.some(e=>e.className==='v13-modal'&&e.innerHTML.includes('ABYSS-DAILY-')),'Daily modal failed');window.__abyssalV13.openAchievements();assert(body.children.some(e=>e.className==='v13-modal'&&e.innerHTML.includes('Field achievements')),'Achievements modal failed');assert.deepEqual(game.scene.audio.last,[.85,.7]);console.log('v1.3 runtime smoke: OK (toolbar + settings + daily + achievements + audio mix)')})().catch(e=>{console.error(e);process.exit(1)})
