const assert=require('assert'),path=require('path');const {pathToFileURL}=require('url')
class ClassList{constructor(){this.s=new Set()}add(...x){x.forEach(v=>this.s.add(v))}remove(...x){x.forEach(v=>this.s.delete(v))}toggle(v,on){if(on===undefined){if(this.s.has(v)){this.s.delete(v);return false}this.s.add(v);return true}on?this.s.add(v):this.s.delete(v);return on}contains(v){return this.s.has(v)}}
class El{constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.style={};this.classList=new ClassList();this.hidden=false;this._html='';this.textContent='';this.parentElement=null;this.attributes={}}set id(v){this._id=v;byId.set(v,this)}get id(){return this._id}set className(v){this._className=v;String(v).split(/\s+/).filter(Boolean).forEach(x=>this.classList.add(x))}get className(){return this._className||''}set innerHTML(v){this._html=String(v)}get innerHTML(){return this._html}append(...els){for(const e of els){e.parentElement=this;this.children.push(e)}}prepend(e){e.parentElement=this;this.children.unshift(e)}remove(){if(this.parentElement)this.parentElement.children=this.parentElement.children.filter(x=>x!==this);if(this.id)byId.delete(this.id)}setAttribute(k,v){this.attributes[k]=String(v)}focus(){}querySelector(){return null}closest(){return null}}
const byId=new Map(),body=new El('body'),shell=new El('main'),start=new El('section'),badge=new El('span');shell.className='shell';start.id='start-panel';badge.id='badge';body.append(shell);shell.append(badge,start)
const listeners=new Map();global.document={body,documentElement:new El('html'),querySelector(sel){if(sel==='.shell')return shell;return null},getElementById(id){return byId.get(id)||null},createElement(tag){return new El(tag)},addEventListener(name,fn){const a=listeners.get(name)||[];a.push(fn);listeners.set(name,a)}}
global.MutationObserver=class{constructor(fn){this.fn=fn}observe(){}disconnect(){}}
const store=new Map();global.localStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)}
global.window={__abyssal:null,__abyssalV12:null,__abyssalV13:null}
let state={mode:'title',hasSave:true,seed:'ABYSS-TEST',floor:1,floorName:'The Drowned Observatory',objective:'Begin an expedition.',dead:false,reducedMotion:true,runStats:{damageTaken:0},secretCount:0,steps:0}
const events={};const game={events:{on(n,fn){events[n]=fn}}};let sent=[]
window.__abyssal={send:a=>sent.push(a),getState:()=>structuredClone(state),getGame:()=>game,getLanguage:()=> 'en'}
window.__abyssalV12={getCodex:()=>({enemies:[],items:[],floors:[],endings:[],secrets:[]}),openCodex(){this.opened=true}}
window.__abyssalV13={getAchievements:()=>({unlocked:[]}),openDaily(){this.daily=true},openAchievements(){this.ach=true},openSettings(){this.settings=true}}
;(async()=>{await import(pathToFileURL(path.resolve(__dirname,'../docs/v14.js')).href+`?t=${Date.now()}`);assert(window.__abyssalV14,'v1.4 runtime API missing');const home=byId.get('v14-home');assert(home&&!home.hidden,'home screen did not mount');assert(home.innerHTML.includes('Resume expedition')&&home.innerHTML.includes('New expedition'),'home actions missing');window.__abyssalV14.newExpedition();assert(home.hidden,'new expedition should hide home');assert(byId.get('v14-back'),'profile back button missing');window.__abyssalV14.showHome();assert(!home.hidden,'showHome failed');state={...state,mode:'playing',floor:2,floorName:'The City Below',objective:'Find the bell tower.'};events.snapshot?.(structuredClone(state));const stage=byId.get('v14-stage');assert(stage&&!stage.hidden&&stage.innerHTML.includes('Act'),'act transition did not render');console.log('v1.4 runtime smoke: OK (home + profile navigation + act transition)')})().catch(e=>{console.error(e);process.exit(1)})
