const assert=require('assert'),fs=require('fs'),path=require('path')
const root=path.resolve(__dirname,'..'),docs=path.join(root,'docs')
for(const f of ['v14.js','v14.css'])assert(fs.existsSync(path.join(docs,f)),`Missing ${f}`)
const js=fs.readFileSync(path.join(docs,'v14.js'),'utf8'),css=fs.readFileSync(path.join(docs,'v14.css'),'utf8'),html=fs.readFileSync(path.join(docs,'index.html'),'utf8'),sw=fs.readFileSync(path.join(docs,'sw.js'),'utf8')
for(const marker of ['data-v14="resume"','data-v14="new"','data-v14="daily"','data-v14="codex"','data-v14="achievements"','data-v14="settings"','FINAL · v1.4.0','showAct','showBoss','calculateDailyScore'])assert(js.includes(marker),`v1.4 JS marker missing: ${marker}`)
for(const marker of ['.v14-home','.v14-stage','.v14-home-actions','.v14-stage-stats','prefers-reduced-motion'])assert(css.includes(marker),`v1.4 CSS marker missing: ${marker}`)
assert(html.includes('./v14.css')&&html.includes('./v14.js'),'v1.4 assets missing from index')
assert(sw.includes('abyssal-descent-v1.4.0')&&sw.includes('./v14.js')&&sw.includes('./v14.css'),'v1.4 assets/version missing from service worker')
for(const phrase of ['Nueva expedición','Descenso diario','Logros','Opciones','New expedition','Daily Descent','Achievements','Options'])assert(js.includes(phrase),`Presentation i18n marker missing: ${phrase}`)
const dungeon=fs.readFileSync(path.join(docs,'game/DungeonScene.js'),'utf8');for(const marker of ['presentEndingChoices','gainSecret','startBoss','useAbility','saveGame','loadGame','drawMinimap'])assert(dungeon.includes(marker),`Core parity marker missing: ${marker}`)
console.log('v1.4 presentation check: OK (home + navigation + act/boss cards + daily result + EN/ES)')
