const assert=require('assert'),fs=require('fs'),path=require('path')
const docs=path.resolve(__dirname,'../docs')
for(const f of ['v14.js','v14.css','v23-c64.js','v23.css'])assert(fs.existsSync(path.join(docs,f)),`Missing ${f}`)
const js=fs.readFileSync(path.join(docs,'v14.js'),'utf8'),css=fs.readFileSync(path.join(docs,'v14.css'),'utf8'),html=fs.readFileSync(path.join(docs,'index.html'),'utf8'),sw=fs.readFileSync(path.join(docs,'sw.js'),'utf8'),boot=fs.readFileSync(path.join(docs,'bootstrap.js'),'utf8')
assert(!js.includes('new MutationObserver'),'presentation MutationObserver forbidden: it can deadlock title/profile navigation')
for(const marker of ['data-v14="resume"','data-v14="new"','data-v14="daily"','data-v14="codex"','data-v14="achievements"','data-v14="settings"','showAct','showBoss','calculateDailyScore'])assert(js.includes(marker),`v14 marker missing: ${marker}`)
for(const marker of ['z-index:900','z-index:1400','.v14-home','.v14-stage'])assert(css.includes(marker),`v14 CSS marker missing: ${marker}`)
assert(html.includes('./v23.css?v=2.3.0')&&html.includes('./bootstrap.js?v=2.3.0'),'v2.3 assets missing from index')
assert(sw.includes('abyssal-descent-v2.3.0-r1')&&sw.includes('./v23-c64.js')&&sw.includes('./v23.css'),'v2.3 assets missing from service worker')
assert(boot.includes("await import('./v23-c64.js?v=2.3.0')")&&!/v15-renderer|v20-premium|v21-art|v22-art/.test(boot),'bootstrap must load only the C64 renderer')
console.log('v2.3 presentation check: OK (title routes + C64 renderer + no stacked renderers)')
